name: Codecov Docker

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.9'
    steps:
    - uses: actions/checkout@v2
    - name: Install Conda environment from environment.yml
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: conda-requirements.txt
        environment-name: codecov-requirements

    - name: Generate Report
      run: |
        mamba install coverage
        coverage run -m unittest
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2
  