name: Codecov Docker

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image and upload coverage
      run: docker build . --file tobac/tests/Dockerfile-coverage
