name: Codecov Docker

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: codecov/codecov-action@v2
    - name: Build the Docker image and upload coverage
      with: 
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        run: docker build . --file tobac/tests/Dockerfile-coverage -e CI=true
